fix(user-popover): add explicit type for luUser signal (#4362)
## Description

Fix type in user-popover component

-----

Apps using this component fail to build when not using `skipLibCheck:
true` with the following error :
```
[ERROR] TS2307: Cannot find module '@lucca-front/ng/types/lucca-front-ng-user' or its corresponding type declarations. [plugin angular-compiler]

    node_modules/@lucca-front/ng/types/lucca-front-ng-user-popover.d.ts:4:59:
      4 │ ...cca_front_ng_user from '@lucca-front/ng/types/lucca-front-ng-user';
        ╵                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

The compiler outputs the wrong import path to `ILuUser` when inferring
the type of the `luUser` property, probably caused by a typescript 5.9
change.

-----